### ISSUE TITLE
Value cannot be null. (Parameter 'path 1')

### ISSUE THREAD

**Issue by fideliochan** [enescaakir/MHRS-OtomatikRandevu#9]
latest repo.
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at MHRS_OtomatikRandevu.Program.GetToken(IClientService client) in C:\Users\REDACTED\Source\Repos\MHRS-OtomatikRandevuu\MHRS-OtomatikRandevu\Program.cs:line 347
   at MHRS_OtomatikRandevu.Program.Main(String[] args) in C:\Users\REDACTED\Source\Repos\MHRS-OtomatikRandevuu\MHRS-OtomatikRandevu\Program.cs:line 43
   ```

**Comment by enescaakir** [comment]
Fixed.
